home:
    path: /
    controller: App\Controller\HomeController::index

avocat_list:
    path: /avocats
    controller: App\Controller\AvocatController::list

avocat_new:
    path: /admin/avocat/new
    controller: App\Controller\AvocatController::new
    methods: [GET, POST]

recap:
    path: /recap
    controller: App\Controller\AccountController::index

convert:
    path: /convert
    controller: App\Controller\ConvertController::convert

weather:
    path: /weather/{city}
    controller: App\Controller\WeatherController::weather
    methods: [GET]

controllers:
    resource: ../src/Controller/
    type: attribute

login:
    path: /login
    controller: App\Controller\SecuriteController::login

logout:
    path: /logout
    controller: App\Controller\SecuriteController::logout

