home:
    path: /
    controller: App\Controller\HomeController::index

lawyer_profile_complete:
    path: /profile/lawyer/complete
    controller: App\Controller\LawyerController::completeProfile

user_list:
    path: /trouver-un-avocat
    controller: App\Controller\AvocatController::listAvocats

new_avocat:
    path: /avocat/new-avocat
    controller: App\Controller\AvocatController::new
    methods: [GET, POST]

convert:
    path: /convert
    controller: App\Controller\ConvertController::convert

weather:
    path: /weather/{city}
    controller: App\Controller\WeatherController::weather

mon_compte:
    path: /mon-compte
    controller: App\Controller\AccountController::index

controllers:
    resource: ../src/Controller/
    type: attribute

login:
    path: /login
    controller: App\Controller\SecuriteController::login

