parameters:
    photos_directory: '%kernel.project_dir%/public/uploads/photos'
    cloudconvert_api_key: 'TRE_CLE_API_CLOUDCONVERT'
    documents_directory: '%kernel.project_dir%/public/uploads/documents'


services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $photosDirectory: '%photos_directory%' 

    # rend les classes dans src/ disponibles pour être utilisées comme services
    # cela crée un service par classe dont l'id est le nom complet de la classe
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    # ajoutez plus de définitions de services lorsque vous avez besoin d'une configuration explicite
    # notez que les dernières définitions remplacent toujours les précédentes
